name: build and deploy docs

on:
  push:
    branches:
      main

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: docs
    env:
      working-directory: docs
    steps:
      # 実行環境セットアップ
      ## コードをチェックアウト
      - name: checkout source
        uses: actions/checkout@v3
      ## Node.jsのセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'npm' # npmキャッシュを有効化
          cache-dependency-path: ${{ env.working-directory }}/package-lock.json
      ## 依存ライブラリのインストール
      - name: Install dependencies
        run: npm ci
      - run: npm build

      # レポート公開(公開先：GitHub Pages)
      - name: upload report
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.working-directory }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
